// Types, data loader, and the single source of truth for filtering/faceting the
// case-study library. Both the public page (server) and the /api/case-studies route
// import from here so the filtering logic never drifts between them.
//
// The dataset is generated by scripts/build-case-studies.mjs from the outreach bot's
// past_projects.json. Re-run that script whenever the source data changes.

import rawStudies from "@/features/01-case-study-engine/data/case_studies.json";

export type CaseStudy = {
  id: string;
  /** Display name. Real client name, or an alias if anonymized. */
  name: string;
  anonymized: boolean;
  /** Clean, normalized practice areas (the filter facets). */
  practiceAreas: string[];
  /** Raw source keywords — kept for search recall, not rendered as chips. */
  keywords: string[];
  /** Deliverables prose, or a graceful placeholder when the source had none. */
  summary: string;
  hasDetails: boolean;
  semester: string;
  season: string; // "Fall" | "Spring" | ""
  year: number;
  termLabel: string; // e.g. "Spring 2024"
  termIndex: number; // sortable; higher = more recent
  /** How many semesters CUBE worked with this client. */
  engagements: number;
  repeatClient: boolean;
};

/** Canonical display order for practice-area chips and filters. */
export const PRACTICE_AREA_ORDER = [
  "Strategy & Research",
  "Marketing & Brand",
  "Software & Data",
  "AI & Machine Learning",
  "Product & Hardware",
  "Finance & Operations",
  "General Consulting",
] as const;

export type SortKey = "newest" | "oldest" | "az";

export const SORT_OPTIONS: { key: SortKey; label: string }[] = [
  { key: "newest", label: "Newest first" },
  { key: "oldest", label: "Oldest first" },
  { key: "az", label: "Client A–Z" },
];

const ALL_STUDIES = rawStudies as unknown as CaseStudy[];

export function getCaseStudies(): CaseStudy[] {
  return ALL_STUDIES;
}

export type Facets = {
  total: number;
  distinctClients: number;
  yearsActive: number;
  practiceAreas: { area: string; count: number }[];
  terms: string[];
};

export function getFacets(studies: CaseStudy[] = ALL_STUDIES): Facets {
  const areaCounts = new Map<string, number>();
  const names = new Set<string>();
  const years: number[] = [];
  const termsSeen: string[] = [];
  const termSet = new Set<string>();

  for (const s of studies) {
    for (const a of s.practiceAreas) areaCounts.set(a, (areaCounts.get(a) ?? 0) + 1);
    if (s.name) names.add(s.name.toLowerCase());
    if (s.year) years.push(s.year);
    if (s.termLabel && !termSet.has(s.termLabel)) {
      termSet.add(s.termLabel);
      termsSeen.push(s.termLabel); // studies arrive newest-first, so this stays ordered
    }
  }

  const practiceAreas = PRACTICE_AREA_ORDER
    .filter((a) => areaCounts.has(a))
    .map((area) => ({ area, count: areaCounts.get(area) ?? 0 }));

  const yearsActive = years.length ? Math.max(...years) - Math.min(...years) + 1 : 0;

  return {
    total: studies.length,
    distinctClients: names.size,
    yearsActive,
    practiceAreas,
    terms: termsSeen,
  };
}

export type FilterOptions = {
  query?: string;
  areas?: string[];
  term?: string; // termLabel, or "" / "all" for no filter
  sort?: SortKey;
};

function haystack(s: CaseStudy): string {
  return [s.name, s.summary, s.termLabel, ...s.practiceAreas, ...s.keywords]
    .join(" ")
    .toLowerCase();
}

/** Pure filter+sort used by both the client UI and the API route. */
export function filterCaseStudies(studies: CaseStudy[], opts: FilterOptions = {}): CaseStudy[] {
  const tokens = (opts.query ?? "").toLowerCase().split(/\s+/).filter(Boolean);
  const areas = opts.areas?.filter(Boolean) ?? [];
  const term = opts.term && opts.term !== "all" ? opts.term : "";

  let out = studies.filter((s) => {
    if (term && s.termLabel !== term) return false;
    if (areas.length && !areas.some((a) => s.practiceAreas.includes(a))) return false;
    if (tokens.length) {
      const hay = haystack(s);
      if (!tokens.every((t) => hay.includes(t))) return false;
    }
    return true;
  });

  const sort = opts.sort ?? "newest";
  out = [...out].sort((a, b) => {
    if (sort === "az") return a.name.localeCompare(b.name);
    if (sort === "oldest") return a.termIndex - b.termIndex || a.name.localeCompare(b.name);
    return b.termIndex - a.termIndex || a.name.localeCompare(b.name); // newest
  });

  return out;
}
